version: '3'
services:
  go:
    container_name: go
    build: docker/go
    volumes:
      - './src:/app/src/app'
      - 'go-state:/app/pkg'
    working_dir: /app/src/app
    environment:
      GOPATH: /app
      CGO_ENABLED: 0
      GOOS: linux
      GO111MODULE: "on"
volumes:
  go-state: